### ISSUE TITLE
site_centers.mat?

### ISSUE THREAD

**Issue by mpinsky** [miriamwanner/kelpsynchrony#1]
Dear @miriamwanner ,

I notice that the init_data_processing.R code requires a site_centers.mat file. Would you be able to add that to the repo or point to where it is? 

Thanks! I'm trying to run your code as a way to learn more about these datasets.

Regards
Malin Pinsky

**Comment by mpinsky** [comment]
Or perhaps they are here? https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-sbc.158.1

**Comment by miriamwanner** [comment]
Hi @mpinsky,

They must have been missing! Just added them.
